services:
  db_tested:
    image: postgres:17-alpine
    container_name: db_tested
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME:-tested}
    ports:
      - "5432:5432"
    volumes:
      - ./db-tested-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_tested_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_internal:
    image: postgres:17-alpine
    container_name: db_internal
    restart: always
    environment:
      POSTGRES_USER: ${INTERNAL_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${INTERNAL_DB_PASS}
      POSTGRES_DB: ${INTERNAL_DB_NAME:-internal}
    ports:
      - "5433:5432"
    volumes:
      - ./db-internal-int.sql:/docker-entrypoint-initdb.d/init.sql
      - db_internal_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_tested_data:
  db_internal_data:
