/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultsImport } from './routes/results'
import { Route as IndexImport } from './routes/index'
import { Route as ChecksCheckNameHistoryImport } from './routes/checks.$checkName.history'

// Create/Update Routes

const ResultsRoute = ResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChecksCheckNameHistoryRoute = ChecksCheckNameHistoryImport.update({
  id: '/checks/$checkName/history',
  path: '/checks/$checkName/history',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsImport
      parentRoute: typeof rootRoute
    }
    '/checks/$checkName/history': {
      id: '/checks/$checkName/history'
      path: '/checks/$checkName/history'
      fullPath: '/checks/$checkName/history'
      preLoaderRoute: typeof ChecksCheckNameHistoryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/checks/$checkName/history': typeof ChecksCheckNameHistoryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/checks/$checkName/history': typeof ChecksCheckNameHistoryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/checks/$checkName/history': typeof ChecksCheckNameHistoryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/results' | '/checks/$checkName/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/results' | '/checks/$checkName/history'
  id: '__root__' | '/' | '/results' | '/checks/$checkName/history'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRoute: typeof ResultsRoute
  ChecksCheckNameHistoryRoute: typeof ChecksCheckNameHistoryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRoute: ResultsRoute,
  ChecksCheckNameHistoryRoute: ChecksCheckNameHistoryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/results",
        "/checks/$checkName/history"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/results": {
      "filePath": "results.tsx"
    },
    "/checks/$checkName/history": {
      "filePath": "checks.$checkName.history.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
