spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    tested:
      url: ${TESTED_DB_URL}
      username: ${TESTED_DB_USER}
      password: ${TESTED_DB_PASS}
    internal:
      url: ${INTERNAL_DB_URL}
      username: ${INTERNAL_DB_USER}
      password: ${INTERNAL_DB_PASS}

app:
  loader:
    checks-path: checks
  db:
    query-timeout-seconds: ${QUERY_TIMEOUT_SECONDS}
    internal:
      init-script-path: classpath:schema/internal.sql
